export interface Item {
    id: number,
    locationId:   number,
    itemStatusId: number,
    name: string,
    model: string,
    brand: string,
    image?: string,
    yearBought: Date,
    active: boolean,
    number: string,
    notes?: string,
    schoolNumber?: string,
    location: {id: number, name: string},
}